import type { WorkflowRecipe } from './types.js'

export const workflowRecipeCatalog: WorkflowRecipe[] = [
  {
    id: 'quick-json-demo',
    name: 'JSON 快速演示',
    description: '适合用最小 JSON 样例快速搭一个可运行分析流程。',
    appliesToModes: ['create'],
    keywords: ['json', '快速', '演示', '样例', '最小', 'pearson', '相关'],
    minimalPattern: ['manual-json-import', 'pearson'],
    preferredEntryNodes: ['manual-json-import'],
    preferredTerminalNodes: ['pearson', 'spearman', 'kendall'],
    requiresSchemaInspection: true,
  },
  {
    id: 'single-table-correlation',
    name: '单表相关性分析',
    description: '适合单张表上的 Pearson、Spearman、Kendall 相关分析。',
    appliesToModes: ['create', 'edit'],
    keywords: ['相关', '相关性', 'pearson', 'spearman', 'kendall'],
    minimalPattern: ['manual-json-import', 'pearson'],
    preferredEntryNodes: ['manual-json-import', 'file-import', 'neighbor-system'],
    preferredTerminalNodes: ['pearson', 'spearman', 'kendall'],
    requiresSchemaInspection: true,
  },
  {
    id: 'single-table-regression',
    name: '单表回归分析',
    description: '适合单张表上的线性回归、Lasso 或随机森林特征重要性分析。',
    appliesToModes: ['create', 'edit'],
    keywords: ['回归', 'lasso', '线性回归', '随机森林', '特征重要性'],
    minimalPattern: ['manual-json-import', 'multiple-linear-regression'],
    preferredEntryNodes: ['manual-json-import', 'file-import', 'neighbor-system'],
    preferredTerminalNodes: ['multiple-linear-regression', 'lasso', 'random-forest-feature-importance'],
    requiresSchemaInspection: true,
  },
  {
    id: 'multi-source-merge-analysis',
    name: '多来源合并分析',
    description: '适合多个来源按键关联或追加后再分析。',
    appliesToModes: ['create', 'edit'],
    keywords: ['合并', 'merge', '多来源', '多个来源', '两份', '两个来源', 'sn', '关联'],
    minimalPattern: ['file-import', 'file-import', 'data-merge', 'multiple-linear-regression'],
    preferredEntryNodes: ['file-import', 'manual-json-import', 'neighbor-system'],
    preferredTerminalNodes: ['multiple-linear-regression', 'pearson', 'random-forest-feature-importance'],
    requiresSchemaInspection: true,
  },
  {
    id: 'xgboost-shap-analysis',
    name: 'XGBoost SHAP 分析',
    description: '适合需要模型解释和 SHAP 输出的分析场景。',
    appliesToModes: ['create', 'edit'],
    keywords: ['xgboost', 'shap', '解释', '特征解释'],
    minimalPattern: ['manual-json-import', 'xgboost-shap'],
    preferredEntryNodes: ['manual-json-import', 'file-import', 'neighbor-system'],
    preferredTerminalNodes: ['xgboost-shap'],
    requiresSchemaInspection: true,
  },
]
